# Generated by Django 6.0.4 on 2026-04-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputlayer",
            name="name",
            field=models.CharField(default="DEFAULT", max_length=50),
        ),
    ]
