# Generated by Django 6.0.4 on 2026-04-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_inputlayer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiverSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_width", models.IntegerField(default=10)),
                ("river_threshold", models.FloatField(default=0.01)),
                ("river_threshold_end", models.FloatField(default=0.5)),
                ("width_beta", models.FloatField(default=0.5)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.profile"
                    ),
                ),
            ],
        ),
    ]
