# Generated by Django 6.0.4 on 2026-04-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_riversettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riversettings",
            name="river_threshold",
            field=models.FloatField(default=0.02),
        ),
        migrations.AlterField(
            model_name="riversettings",
            name="river_threshold_end",
            field=models.FloatField(default=0.6),
        ),
    ]
