# Generated by Django 6.0.4 on 2026-04-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_riversettings_river_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputlayer",
            name="warping",
            field=models.FloatField(default=0.1, verbose_name="Warping:"),
        ),
        migrations.AlterField(
            model_name="inputlayer",
            name="amplitude",
            field=models.FloatField(default=1.0, verbose_name="Amplitude:"),
        ),
        migrations.AlterField(
            model_name="inputlayer",
            name="frequency",
            field=models.FloatField(default=0.1, verbose_name="Frequency:"),
        ),
        migrations.AlterField(
            model_name="inputlayer",
            name="lacunarity",
            field=models.FloatField(default=2.0, verbose_name="Lacunarity:"),
        ),
        migrations.AlterField(
            model_name="inputlayer",
            name="name",
            field=models.CharField(
                default="DEFAULT", max_length=50, verbose_name="Name:"
            ),
        ),
        migrations.AlterField(
            model_name="inputlayer",
            name="octaves",
            field=models.IntegerField(default=3, verbose_name="Octaves:"),
        ),
        migrations.AlterField(
            model_name="inputlayer",
            name="persistence",
            field=models.FloatField(default=0.5, verbose_name="Persistence:"),
        ),
        migrations.AlterField(
            model_name="riversettings",
            name="max_width",
            field=models.IntegerField(default=10, verbose_name="Max Width:"),
        ),
        migrations.AlterField(
            model_name="riversettings",
            name="river_threshold",
            field=models.FloatField(default=0.02, verbose_name="River Threshold:"),
        ),
        migrations.AlterField(
            model_name="riversettings",
            name="river_threshold_end",
            field=models.FloatField(default=0.6, verbose_name="River Threshold End:"),
        ),
        migrations.AlterField(
            model_name="riversettings",
            name="width_beta",
            field=models.FloatField(default=0.5, verbose_name="Width Beta:"),
        ),
    ]
