# Generated by Django 6.0.4 on 2026-04-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_inputlayer_warping_alter_inputlayer_amplitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputlayer",
            name="ridge_strength",
            field=models.FloatField(default=0.3, verbose_name="Ridge Strength:"),
        ),
    ]
