# Generated by Django 6.0.4 on 2026-05-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_inputlayer_ridge_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='riversettings',
            name='has_erosion',
            field=models.BooleanField(default=True, verbose_name='Erosion:'),
        ),
        migrations.AddField(
            model_name='riversettings',
            name='has_rivers',
            field=models.BooleanField(default=True, verbose_name='Rivers:'),
        ),
        migrations.AddField(
            model_name='riversettings',
            name='has_water',
            field=models.BooleanField(default=True, verbose_name='Water:'),
        ),
    ]
