# Generated by Django 6.0.4 on 2026-05-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_riversettings_has_erosion_riversettings_has_rivers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", models.CharField(default="Terrain!", verbose_name="Seed:")),
                (
                    "has_erosion",
                    models.BooleanField(default=True, verbose_name="Erosion:"),
                ),
                ("has_water", models.BooleanField(default=True, verbose_name="Water:")),
                (
                    "has_rivers",
                    models.BooleanField(default=True, verbose_name="Rivers:"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="riversettings",
            name="has_erosion",
        ),
        migrations.RemoveField(
            model_name="riversettings",
            name="has_rivers",
        ),
        migrations.RemoveField(
            model_name="riversettings",
            name="has_water",
        ),
    ]
