# Generated by Django 6.0.4 on 2026-05-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_featuresettings_remove_riversettings_has_erosion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuresettings",
            name="profile",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="featuresettings",
            name="seed",
            field=models.CharField(
                default="Terrain!", max_length=255, verbose_name="Seed:"
            ),
        ),
    ]
