# Generated by Django 6.0.4 on 2026-05-04 20:15

from django.db import migrations


def create_feature_settings(apps, schema_editor):
    Profile = apps.get_model("app1", "Profile")
    FeatureSettings = apps.get_model("app1", "FeatureSettings")

    FeatureSettings.objects.bulk_create([
        FeatureSettings(profile=profile)
        for profile in Profile.objects.all()
        if not FeatureSettings.objects.filter(profile=profile).exists()
    ])


def delete_feature_settings(apps, schema_editor):
    FeatureSettings = apps.get_model("app1", "FeatureSettings")
    FeatureSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_featuresettings_profile_alter_featuresettings_seed"),
    ]

    operations = [
        migrations.RunPython(
            create_feature_settings,
            delete_feature_settings,
        ),
    ]

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ("app1", "0009_featuresettings_profile_alter_featuresettings_seed"),
#     ]

#     operations = []
