# Generated by Django 6.0.4 on 2026-05-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_create_feature_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuresettings",
            name="has_erosion",
            field=models.BooleanField(default=True, verbose_name="Erosion"),
        ),
        migrations.AlterField(
            model_name="featuresettings",
            name="has_rivers",
            field=models.BooleanField(default=True, verbose_name="Rivers"),
        ),
        migrations.AlterField(
            model_name="featuresettings",
            name="has_water",
            field=models.BooleanField(default=True, verbose_name="Water"),
        ),
        migrations.AlterField(
            model_name="featuresettings",
            name="seed",
            field=models.CharField(
                blank=True, default="Terrain!", max_length=255, verbose_name="Seed:"
            ),
        ),
    ]
